grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.homelab
  additionalDataSources:
  - name: loki
    access: proxy
    editable: false
    type: loki
    url: http://loki-gateway.loki
    version: 1


prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    