apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    # path: k8s
    repoURL: https://gitlab.com/gitops-demo18/infrastructure/bookinfo
    targetRevision: HEAD
