apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/instrumented-app.yaml
    repoURL: https://github.com/pliniogsnascimento/argocd-applications.git
    targetRevision: HEAD
