apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instrumented-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/pliniogsnascimento/argocd-applications.git
    targetRevision: HEAD
    directory:
      include: 'instrumented-app.yaml'
