apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: platform
  source:
    path: src/istio/istio-base
    repoURL: https://github.com/pliniogsnascimento/k8s-platform-tools.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: platform
  source:
    path: src/istio/istiod
    repoURL: https://github.com/pliniogsnascimento/k8s-platform-tools.git
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: platform
  source:
    path: src/istio/gateway
    repoURL: https://github.com/pliniogsnascimento/k8s-platform-tools.git
    targetRevision: HEAD
