apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: platform
  sources:
  - chart: base
    helm:
      releaseName: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.2
    valueFiles:
    - $values/values/istio-base.yaml
  - repoURL: 'https://github.com/pliniogsnascimento/argocd-applications.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: platform
  sources:
  - chart: istiod
    helm:
      releaseName: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.2
    valueFiles:
    - $values/values/istiod.yaml
  - repoURL: 'https://github.com/pliniogsnascimento/argocd-applications.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: platform
  sources:
  - chart: gateway
    helm:
      releaseName: istio-ingressgateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.2
    valueFiles:
    - $values/values/istio-ingress.yaml
  - repoURL: 'https://github.com/pliniogsnascimento/argocd-applications.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
