apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: src/kyverno
    # TODO: Change this to official helm repo
    repoURL: https://github.com/pliniogsnascimento/k8s-platform-tools.git
    targetRevision: HEAD
