apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: src
    repoURL: https://gitlab.com/gitops-demo18/infrastructure/litmus.git
    targetRevision: HEAD
