apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  project: platform
  source:
    path: src/nginx-ingress
    repoURL: https://github.com/pliniogsnascimento/k8s-platform-tools.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  #     prune: true