apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: platform
  sources:
  - repoURL: 'https://github.com/pliniogsnascimento/argocd-applications.git'
    targetRevision: HEAD
    ref: values
  - chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - $values/values/ingress-nginx.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  #   automated:
  #     selfHeal: true
  #     prune: true
