apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-jobs
  name: app-jobs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-jobs
  template:
    metadata:
      labels:
        app: app-jobs
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - image: pliniogsnascimento/jobs-api
        name: jobs-api
        resources: {}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgresql.postgresql:5432/jobsdb
